const htmx = {
	ajax: null,
	addClass: null,
	closest: null,
	config: {
		addedClass: 'htmx-added',
		allowEval: true,
		allowNestedOobSwaps: true,
		allowScriptTags: true,
		attributesToSettle: ['class', 'style', 'width', 'height'],
		defaultFocusScroll: false,
		defaultSettleDelay: 20,
		defaultSwapDelay: 0,
		defaultSwapStyle: 'innerHTML',
		disableInheritance: false,
		disableSelector: '[hx-disable], [data-hx-disable]',
		getCacheBusterParam: false,
		globalViewTransitions: false,
		historyCacheSize: 10,
		historyEnabled: true,
		ignoreTitle: false,
		includeIndicatorStyles: true,
		indicatorClass: 'htmx-indicator',
		inlineScriptNonce: '',
		inlineStyleNonce: '',
		methodsThatUseUrlParams: ['get', 'delete'],
		refreshOnHistoryMiss: false,
		requestClass: 'htmx-request',
		responseHandling: [
			{ code: '204', swap: false },
			{ code: '[23]..', swap: true },
			{ code: '[45]..', swap: false, error: true },
		],
		scrollBehavior: 'instant',
		scrollIntoViewOnBoost: true,
		selfRequestsOnly: true,
		settlingClass: 'htmx-settling',
		swappingClass: 'htmx-swapping',
		timeout: 0,
		triggerSpecsCache: null,
		withCredentials: false,
		wsBinaryType: 'blob',
		wsReconnectDelay: 'full-jitter',
	},
	defineExtension: null,
	find: null,
	findAll: null,
	logAll: null,
	logNone: null,
	logger: null,
	off: null,
	on: null,
	onLoad: null,
	parseInterval: null,
	process: null,
	remove: null,
	removeClass: null,
	removeExtension: null,
	swap: null,
	takeClass: null,
	toggleClass: null,
	trigger: null,
	values: values,
	version: '2.0.3',
	_: null,
};
